apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5n  # encodé en base64 pour "spring"
  SPRING_DATASOURCE_PASSWORD: MjMyNQ==  # encodé en base64 pour "2325"
